import 'package:freezed_annotation/freezed_annotation.dart';

part 'pokemon_detail.freezed.dart';
part 'pokemon_detail.g.dart';

/// Full detail for a single Pokémon from `GET /pokemon/{id}`.
///
/// Immutable value object generated by [freezed]. All fields map 1-to-1 to
/// the PokéAPI JSON schema. Heights are in decimetres, weights in hectograms
/// (divide by 10 to get metres / kilograms).
@freezed
class PokemonDetail with _$PokemonDetail {
  const factory PokemonDetail({
    /// National Pokédex number.
    required int id,

    /// Lowercase English name as returned by the API.
    required String name,

    /// Height in **decimetres** (divide by 10 for metres).
    required int height,

    /// Weight in **hectograms** (divide by 10 for kilograms).
    required int weight,

    /// Base EXP reward when defeated. `null` for some forms / regional variants.
    int? baseExperience,

    /// Ordered list of type slots. `slot == 1` is the primary type.
    required List<PokemonTypeSlot> types,

    /// Base stat values (HP, ATK, DEF, SP.ATK, SP.DEF, SPD).
    required List<PokemonStatSlot> stats,

    /// Known abilities, including hidden abilities ([PokemonAbilitySlot.isHidden]).
    required List<PokemonAbilitySlot> abilities,

    /// Sprite URLs for this Pokémon.
    required PokemonSprites sprites,
  }) = _PokemonDetail;

  factory PokemonDetail.fromJson(Map<String, dynamic> json) =>
      _$PokemonDetailFromJson(json);
}

/// Associates a [type] with its display [slot] in a multi-type Pokémon.
///
/// Slot 1 = primary type (used for theming); slot 2 = secondary type.
@freezed
class PokemonTypeSlot with _$PokemonTypeSlot {
  const factory PokemonTypeSlot({
    required int slot,
    required NamedResource type,
  }) = _PokemonTypeSlot;

  factory PokemonTypeSlot.fromJson(Map<String, dynamic> json) =>
      _$PokemonTypeSlotFromJson(json);
}

/// One row from the `stats` array in the PokéAPI response.
@freezed
class PokemonStatSlot with _$PokemonStatSlot {
  const factory PokemonStatSlot({
    /// The base stat value shown on a Pokémon's summary screen (0 – 255).
    required int baseStat,

    /// EV yield for this stat when the Pokémon is defeated.
    required int effort,

    /// Stat identity (name: "hp" | "attack" | "defense" | …).
    required NamedResource stat,
  }) = _PokemonStatSlot;

  factory PokemonStatSlot.fromJson(Map<String, dynamic> json) =>
      _$PokemonStatSlotFromJson(json);
}

/// One entry from the `abilities` array in the PokéAPI response.
@freezed
class PokemonAbilitySlot with _$PokemonAbilitySlot {
  const factory PokemonAbilitySlot({
    /// `true` if this is a hidden ability (not obtainable through normal gameplay).
    required bool isHidden,

    /// Display order slot.
    required int slot,

    /// Ability identity (name + canonical URL).
    required NamedResource ability,
  }) = _PokemonAbilitySlot;

  factory PokemonAbilitySlot.fromJson(Map<String, dynamic> json) =>
      _$PokemonAbilitySlotFromJson(json);
}

/// Sprite URL container. Prefer [PokemonOtherSprites.officialArtwork] for
/// high-resolution display; fall back to [frontDefault] for small thumbnails.
@freezed
class PokemonSprites with _$PokemonSprites {
  const factory PokemonSprites({
    /// Low-res game sprite (front, default form). May be `null` for some forms.
    String? frontDefault,

    /// Low-res shiny variant sprite. May be `null`.
    String? frontShiny,

    /// Container for additional artwork beyond the base game sprites.
    required PokemonOtherSprites other,
  }) = _PokemonSprites;

  factory PokemonSprites.fromJson(Map<String, dynamic> json) =>
      _$PokemonSpritesFromJson(json);
}

/// Wrapper for `sprites.other` in the API response.
@freezed
class PokemonOtherSprites with _$PokemonOtherSprites {
  const factory PokemonOtherSprites({
    /// High-resolution official TCG-style artwork. This is the preferred image
    /// for display in this app; `null` for a very small number of edge cases.
    OfficialArtwork? officialArtwork,
  }) = _PokemonOtherSprites;

  factory PokemonOtherSprites.fromJson(Map<String, dynamic> json) =>
      _$PokemonOtherSpritesFromJson(json);
}

/// URLs from `sprites.other.official-artwork`.
@freezed
class OfficialArtwork with _$OfficialArtwork {
  const factory OfficialArtwork({
    /// Default form official artwork URL (PNG, typically 475×475 px).
    String? frontDefault,

    /// Shiny form official artwork URL.
    String? frontShiny,
  }) = _OfficialArtwork;

  factory OfficialArtwork.fromJson(Map<String, dynamic> json) =>
      _$OfficialArtworkFromJson(json);
}

/// Reusable `{ "name": "...", "url": "..." }` object used throughout the API
/// for types, stats, abilities, and other named references.
@freezed
class NamedResource with _$NamedResource {
  const factory NamedResource({required String name, required String url}) =
      _NamedResource;

  factory NamedResource.fromJson(Map<String, dynamic> json) =>
      _$NamedResourceFromJson(json);
}
